name: GitHub App Registration
description: Template to request for a new GitHub App
title: GitHub App Registration
labels: create-app
body:
  - type: markdown
    attributes:
      value: Please provide details for the new GitHub App request
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the GitHub App to be created.
    validations:
      required: true
  - type: input
    id: org
    attributes:
      label: Organisation
      description: Organisation where the GitHub App will be created.
    validations:
      required: true
  - type: markdown
    attributes:
      value: App Permissions
  - type: dropdown
    id: permissions_contents
    attributes:
      label: Contents
      description: Repository contents, commits, branches, downloads, releases, and merges.
      options:
        - noaccess
        - read
        - write
      default: 1
    validations:
      required: true
  - type: dropdown
    id: permissions_issues
    attributes:
      label: Issues
      description: Issues and related comments, assignees, labels, and milestones.
      options:
        - noaccess
        - read
        - write
      default: 0
    validations:
      required: true
  - type: dropdown
    id: permissions_checks
    attributes:
      label: Checks
      description: Checks on code.
      options:
        - noaccess
        - read
        - write
      default: 0
    validations:
      required: true
